# coding=utf-8

data = [
    {
        "id": 0,
        "name": "Instagram",
        "follower_count": 346,
        "description": "Social media platform",
        "country": "United States",
    },
    {
        "id": 1,
        "name": "Cristiano Ronaldo",
        "follower_count": 215,
        "description": "Footballer",
        "country": "Portugal",
    },
    {
        "id": 2,
        "name": "Ariana Grande",
        "follower_count": 183,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "id": 3,
        "name": "Dwayne Johnson",
        "follower_count": 181,
        "description": "Actor and professional wrestler",
        "country": "United States",
    },
    {
        "id": 4,
        "name": "Selena Gomez",
        "follower_count": 174,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "id": 5,
        "name": "Kylie Jenner",
        "follower_count": 172,
        "description": "Reality TV personality and businesswoman and Self-Made Billionaire",
        "country": "United States",
    },
    {
        "id": 6,
        "name": "Kim Kardashian",
        "follower_count": 167,
        "description": "Reality TV personality and businesswoman",
        "country": "United States",
    },
    {
        "id": 7,
        "name": "Lionel Messi",
        "follower_count": 149,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "id": 8,
        "name": "Beyoncé",
        "follower_count": 145,
        "description": "Musician",
        "country": "United States",
    },
    {
        "id": 9,
        "name": "Neymar",
        "follower_count": 138,
        "description": "Footballer",
        "country": "Brasil",
    },
    {
        "id": 10,
        "name": "National Geographic",
        "follower_count": 135,
        "description": "Magazine",
        "country": "United States",
    },
    {
        "id": 11,
        "name": "Justin Bieber",
        "follower_count": 133,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "id": 12,
        "name": "Taylor Swift",
        "follower_count": 131,
        "description": "Musician",
        "country": "United States",
    },
    {
        "id": 13,
        "name": "Kendall Jenner",
        "follower_count": 127,
        "description": "Reality TV personality and Model",
        "country": "United States",
    },
    {
        "id": 14,
        "name": "Jennifer Lopez",
        "follower_count": 119,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "id": 15,
        "name": "Nicki Minaj",
        "follower_count": 113,
        "description": "Musician",
        "country": "Trinidad and Tobago",
    },
    {
        "id": 16,
        "name": "Nike",
        "follower_count": 109,
        "description": "Sportswear multinational",
        "country": "United States",
    },
    {
        "id": 17,
        "name": "Khloé Kardashian",
        "follower_count": 108,
        "description": "Reality TV personality and businesswoman",
        "country": "United States",
    },
    {
        "id": 18,
        "name": "Miley Cyrus",
        "follower_count": 107,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "id": 19,
        "name": "Katy Perry",
        "follower_count": 94,
        "description": "Musician",
        "country": "United States",
    },
    {
        "id": 20,
        "name": "Kourtney Kardashian",
        "follower_count": 90,
        "description": "Reality TV personality",
        "country": "United States",
    },
    {
        "id": 21,
        "name": "Kevin Hart",
        "follower_count": 89,
        "description": "Comedian and actor",
        "country": "United States",
    },
    {
        "id": 22,
        "name": "Ellen DeGeneres",
        "follower_count": 87,
        "description": "Comedian",
        "country": "United States",
    },
    {
        "id": 23,
        "name": "Real Madrid CF",
        "follower_count": 86,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "id": 24,
        "name": "FC Barcelona",
        "follower_count": 85,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "id": 25,
        "name": "Rihanna",
        "follower_count": 81,
        "description": "Musician and businesswoman",
        "country": "Barbados",
    },
    {
        "id": 26,
        "name": "Demi Lovato",
        "follower_count": 80,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "id": 27,
        "name": "Victoria's Secret",
        "follower_count": 69,
        "description": "Lingerie brand",
        "country": "United States",
    },
    {
        "id": 28,
        "name": "Zendaya",
        "follower_count": 68,
        "description": "Actress and musician",
        "country": "United States",
    },
    {
        "id": 29,
        "name": "Shakira",
        "follower_count": 66,
        "description": "Musician",
        "country": "Colombia",
    },
    {
        "id": 30,
        "name": "Drake",
        "follower_count": 65,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "id": 31,
        "name": "Chris Brown",
        "follower_count": 64,
        "description": "Musician",
        "country": "United States",
    },
    {
        "id": 32,
        "name": "LeBron James",
        "follower_count": 63,
        "description": "Basketball player",
        "country": "United States",
    },
    {
        "id": 33,
        "name": "Vin Diesel",
        "follower_count": 62,
        "description": "Actor",
        "country": "United States",
    },
    {
        "id": 34,
        "name": "Cardi B",
        "follower_count": 67,
        "description": "Musician",
        "country": "United States",
    },
    {
        "id": 35,
        "name": "David Beckham",
        "follower_count": 82,
        "description": "Footballer",
        "country": "United Kingdom",
    },
    {
        "id": 36,
        "name": "Billie Eilish",
        "follower_count": 61,
        "description": "Musician",
        "country": "United States",
    },
    {
        "id": 37,
        "name": "Justin Timberlake",
        "follower_count": 59,
        "description": "Musician and actor",
        "country": "United States",
    },
    {
        "id": 38,
        "name": "UEFA Champions League",
        "follower_count": 58,
        "description": "Club football competition",
        "country": "Europe",
    },
    {
        "id": 39,
        "name": "NASA",
        "follower_count": 56,
        "description": "Space agency",
        "country": "United States",
    },
    {
        "id": 40,
        "name": "Emma Watson",
        "follower_count": 56,
        "description": "Actress",
        "country": "United Kingdom",
    },
    {
        "id": 41,
        "name": "Shawn Mendes",
        "follower_count": 57,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "id": 42,
        "name": "Virat Kohli",
        "follower_count": 55,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "id": 43,
        "name": "Gigi Hadid",
        "follower_count": 54,
        "description": "Model",
        "country": "United States",
    },
    {
        "id": 44,
        "name": "Priyanka Chopra Jonas",
        "follower_count": 53,
        "description": "Actress and musician",
        "country": "India",
    },
    {
        "id": 45,
        "name": "9GAG",
        "follower_count": 52,
        "description": "Social media platform",
        "country": "China",
    },
    {
        "id": 46,
        "name": "Ronaldinho",
        "follower_count": 51,
        "description": "Footballer",
        "country": "Brasil",
    },
    {
        "id": 47,
        "name": "Maluma",
        "follower_count": 50,
        "description": "Musician",
        "country": "Colombia",
    },
    {
        "id": 48,
        "name": "Camila Cabello",
        "follower_count": 49,
        "description": "Musician",
        "country": "Cuba",
    },
    {
        "id": 49,
        "name": "NBA",
        "follower_count": 47,
        "description": "Club Basketball Competition",
        "country": "United States",
    },
]
